sudo: required
dist: xenial
language: c
compiler:
  - clang
  - gcc
cache: ccache

before_install:
  - echo 'deb http://download.opensuse.org/repositories/home:/Xorg/xUbuntu_16.04/ /' | sudo tee /etc/apt/sources.list.d/home:Xorg.list
  - curl -sSL https://download.opensuse.org/repositories/home:Xorg/xUbuntu_16.04/Release.key | sudo apt-key add -
  - sudo apt-get update -qq
install:
  - sudo apt-get install -y -qq cmake ninja-build nasm gettext libgtk-3-dev libncursesw5-dev libcpuid-dev-git libpci-dev libprocps-dev libgtk-3-0 libncursesw5 libcpuid15-git libpci3 libprocps4

before_script:
  - mkdir build
  - cd build
  - cmake -GNinja -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=/usr -DWITH_GTK=0 ..
script:
  - ninja
  - sudo ninja install
after_success:
  - ninja test
  - sudo CPUX_BCLK=100 cpu-x --issue-fmt
  - cat /tmp/cpu-x.log
  - cat /tmp/cpu-x-daemon.log
  - git clone https://github.com/anrieff/libcpuid.git /tmp/libcpuid && bash "$TRAVIS_BUILD_DIR/scripts/run_libcpuid_tests.sh" "/tmp/libcpuid/tests"

notifications:
  slack:
    on_success: change
    on_failure: always
