name: AppImage Continuous

on:
  push:
    branches:
      - master

jobs:
  linux-appimage-continuous:
    name: Linux x64_64 (Continuous)
    runs-on: ubuntu-16.04

    steps:
    - uses: actions/checkout@v2

    - name: Build CPU-X
      run: bash -x ./scripts/build_ubuntu.sh "RelWithDebInfo" "$GITHUB_WORKSPACE" "$GITHUB_WORKSPACE/AppDir"

    - name: Package CPU-X as an AppImage
      run: bash -x ./scripts/build_appimage.sh "$GITHUB_WORKSPACE" "$GITHUB_WORKSPACE/AppDir"

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: AppImage
        path: AppImage/*

    # - name: Delete old continuous release
    #   uses: dev-drprasad/delete-tag-and-release@v0.1.2
    #   with:
    #     delete_release: true
    #     tag_name: continuous
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Create continuous release
      uses: ncipollo/release-action@v1
      with:
        token: "${{ secrets.GITHUB_TOKEN }}"
        tag: continuous
        name: Continuous build
        commit: ${{ github.sha }}
        draft: false
        prerelease: true
        body: |
          :warning:  **Known issues:** https://github.com/X0rg/CPU-X/wiki/appimage

          :heavy_check_mark:CPU-X AppImage built from latest commit ([${{ github.sha }}](https://github.com/${{ github.repository }}/commit/${{ github.sha }})).

          :scroll: Build log: https://github.com/${{ github.repository }}/commit/${{ github.sha }}/checks?check_suite_id=${{ github.run_id }}
        artifacts: "AppImage/CPU-X-*.AppImage*"
        allowUpdates: true
        replacesArtifacts: true
