name: Update POT file

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  update-pot-file:
    name: Linux x64_64 (L10n)
    runs-on: ubuntu-latest

    steps:
    - name: Check commiter name
      if: ${{ github.event.pusher.name == 'weblate' || github.event.pusher.email == 'hosted@weblate.org' }}
      run: exit 1

    - uses: actions/checkout@v2

    - name: Install packages
      run: sudo apt-get install -y -qq cmake ninja-build gettext

    - name: Disable all options in CMakeLists.txt
      run: sed -i 's/ ON)$/ OFF)/g' "$GITHUB_WORKSPACE/CMakeLists.txt"

    - name: Generate files for build system
      run: cmake -S "$GITHUB_WORKSPACE" -B build -GNinja -DWITH_GETTEXT=1

    - name: Generate new POT file
      run: ninja -C build genpot

    - uses: EndBug/add-and-commit@v7
      with:
        add: 'po'
        message: 'Regen POT file'
        pull_strategy: '--ff-only'
        push: true
